---
version: '2'

services:
  app:
    build: API
    image: kanban_dashboard:0.1
    hostname: KanbanAPI
    container_name: kanban_API
    restart: unless-stopped
    environment:
      FLASK_APP: application.py
      FLASK_ENV: development
      DEBUG: "True"
      APP_PORT: 5000
      POSTGRES_URI: postgresql://root:qwe123@172.100.23.3/kanban
    ports:
      - 80:5000
    networks:
      kanban-net:
        ipv4_address: 172.100.23.2
  database:
    image: postgres:12.3-alpine
    hostname: Kanban - PostgresDB
    container_name: kanban_DB
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: kanban
    volumes:
    - ./database/postgres:/var/lib/postgresql/data
    networks:
      kanban-net:
        ipv4_address: 172.100.23.3

  proxy:
    image: nginx:latest
    hostname: Nginx - Kanban
    container_name: kanban_Proxy
    restart: unless-stopped
    networks:
      kanban-net:
        ipv4_address: 172.100.23.4

networks:
  kanban-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.23.0/24