---
version: '2'

services:
  app:
    build: API
    image: kanban_dashboard:0.1
    hostname: KanbanAPI
    container_name: kanban_API
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: "True"
      DATABASE_URL: sqlite:///tmp/crud.db
    networks:
      kanban-net:
        ipv4_address: 172.100.23.2
  database:
    image: postgres:12.3-alpine
    hostname: Kanban - PostgresDB
    container_name: kanban_DB
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: kanban
    volumes:
    - ./database/postgres:/var/lib/postgresql/data
    networks:
      kanban-net:
        ipv4_address: 172.100.23.3

networks:
  kanban-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.23.0/24