---
version: '2'

services:
  app:
    build: API
    image: python-kanban
    hostname: KanbanDashboard
    container_name: kanbanDashboard
    restart: unless-stopped
    environment:
      FLASK_APP: API
      FLASK_ENV: development
      FLASK_DEBUG: "True"
    volumes:
      - ./API:/KanbanDashboard/API/
    networks:
      kanban-net:
        ipv4_address: 172.100.23.2
  database:
    image: postgres:12.3-alpine
    hostname: Kanban - PostgresDB
    container_name: kanbanDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: kanban
    volumes:
    - ./database/postgres:/var/lib/postgresql/data
    networks:
      kanban-net:
        ipv4_address: 172.100.23.3

networks:
  kanban-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.23.0/24