POST http://localhost:5000/api/insert
Content-Type: application/json

{
  "username": "vinicius_test1_username",
  "full_name": "vinicius_test1_name",
  "email": "vinicius@test2.com",
  "password": "password_test1",
  "cpf": "11111111111",
  "role": 1
}

###
GET http://localhost:5000/api/delete/10
Accept: application/json

###
